SPECMATIC_CONSTANTS:
  name:
    - Idly Vada
    - Garlic Nan
    - Margarita Pizza
  type:
    - food
  id:
    - 1
  productid:
    - 1
'*':
  name: $(name)
  type: $(type)
  inventory:
    - 5
    - 10
  id: $(id)
  productid: $(productid)
  count:
    - 10
BadRequest:
  timestamp:
    - 2025-06-12T12:00:00.000+00:00
  status:
    - 400
  path:
    - /path
PARAMETERS:
  HEADER:
    pageSize:
      - 10
  QUERY:
    type:
      - food
    orderId:
      - 1
Product:
  name: $(name)
  id:
    - 1
    - 2
    - 3
  type: $(type)
  inventory:
    - 10
  description:
    - World's most loved
    - Number one healthy food of the year
