openapi: 3.0.1
info:
  title: New feature
  version: "1"
paths:
  /products:
    get:
      summary: GET /products
      parameters:
      - name: to-date
        in: query
        schema:
          type: string
      - name: from-date
        in: query
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      - name: Authenticate
        in: header
        required: true
        schema:
          type: string
      - name: pageSize
        in: header
        required: true
        schema:
          type: integer
      - name: Connection
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: GET /products
          headers:
            Set-Cookie:
              required: true
              schema:
                type: string
            X-Content-Type-Options:
              required: true
              schema:
                type: string
            X-XSS-Protection:
              required: true
              schema:
                type: integer
            Pragma:
              required: true
              schema:
                type: string
            X-Frame-Options:
              required: true
              schema:
                type: string
            Keep-Alive:
              required: true
              schema:
                type: string
            Connection:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Products_GET_200_application_json_ResponseBody"
    post:
      summary: POST /products
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      - name: Authenticate
        in: header
        required: true
        schema:
          type: string
      - name: Idempotency-Key
        in: header
        required: true
        schema:
          type: string
      - name: Connection
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Products_POST_application_json_RequestBody"
        required: true
      responses:
        "201":
          description: POST /products
          headers:
            Set-Cookie:
              required: true
              schema:
                type: string
            X-Content-Type-Options:
              required: true
              schema:
                type: string
            X-XSS-Protection:
              required: true
              schema:
                type: integer
            Pragma:
              required: true
              schema:
                type: string
            X-Frame-Options:
              required: true
              schema:
                type: string
            Keep-Alive:
              required: true
              schema:
                type: string
            Connection:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products_POST_201_application_json_ResponseBody"
  /orders:
    post:
      summary: POST /orders
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      - name: Authenticate
        in: header
        required: true
        schema:
          type: string
      - name: Idempotency-Key
        in: header
        required: true
        schema:
          type: string
      - name: Connection
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Orders_POST_application_json_RequestBody"
        required: true
      responses:
        "201":
          description: POST /orders
          headers:
            Set-Cookie:
              required: true
              schema:
                type: string
            X-Content-Type-Options:
              required: true
              schema:
                type: string
            X-XSS-Protection:
              required: true
              schema:
                type: integer
            Pragma:
              required: true
              schema:
                type: string
            X-Frame-Options:
              required: true
              schema:
                type: string
            Keep-Alive:
              required: true
              schema:
                type: string
            Connection:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders_POST_201_application_json_ResponseBody"
components:
  schemas:
    Products_POST_application_json_RequestBody:
      required:
      - inventory
      - name
      - type
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        inventory:
          type: integer
    Products_POST_201_application_json_ResponseBody:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
    Products_GET_200_application_json_ResponseBody:
      required:
      - createdOn
      - id
      - inventory
      - name
      - type
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        inventory:
          type: integer
        id:
          type: integer
        createdOn:
          type: string
    Orders_POST_application_json_RequestBody:
      required:
      - count
      - productid
      type: object
      properties:
        productid:
          type: integer
        count:
          type: integer
    Orders_POST_201_application_json_ResponseBody:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
